spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/marketplace
      database: marketplace

  datasource:
    url: jdbc:postgresql://postgres:5432/marketplace
    username: postgres
    password: qwerty
    driver-class-name: org.postgresql.Driver
