spring:
  application:
    name: marketplace-monolith

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml
    enabled: true

server:
  servlet:
    context-path: /backend
  port: 8080
