spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/marketplace
      database: marketplace

  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: postgres
    password: qwerty
    driver-class-name: org.postgresql.Driver
